ALTER TABLE events ADD COLUMN IF NOT EXISTS origin_site VARCHAR(50) DEFAULT 'funlist';
ALTER TABLE events ADD COLUMN IF NOT EXISTS visibility_tags JSON;
ALTER TABLE events ADD COLUMN IF NOT EXISTS confidence_score DECIMAL(3,2) DEFAULT 0.00;
ALTER TABLE events ADD COLUMN IF NOT EXISTS is_ai_enriched BOOLEAN DEFAULT FALSE;
ALTER TABLE events ADD COLUMN IF NOT EXISTS enrichment_data JSONB;
